version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - APP_NAME=${APP_NAME}
          - APP_ENV=${APP_ENV}
          - APP_DEBUG=${APP_DEBUG}
          - APP_URL=${APP_URL}
          - DB_CONNECTION=pgsql
          - DB_HOST=db
          - DB_PORT=5432
          - DB_DATABASE=${DB_DATABASE}
          - DB_USERNAME=${DB_USERNAME}
          - DB_PASSWORD=${DB_PASSWORD}
          - BROADCAST_DRIVER=${BROADCAST_DRIVER}
          - CACHE_DRIVER=${CACHE_DRIVER}
          - FILESYSTEM_DISK=${FILESYSTEM_DISK}
          - QUEUE_CONNECTION=${QUEUE_CONNECTION}
          - SESSION_DRIVER=${SESSION_DRIVER}
          - SESSION_LIFETIME=${SESSION_LIFETIME}
          - REDIS_HOST=${REDIS_HOST}
          - REDIS_PORT=${REDIS_PORT}

    container_name: laravel_shop-${BRANCH_NAME}
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - storage:/usr/share/nginx/html/storage:rw
      - public:/usr/share/nginx/html/public:rw
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "9001:80"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - storage:/usr/share/nginx/html/storage:rw
      - public:/usr/share/nginx/html/public:rw
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: laravel_db-${BRANCH_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /opt/laravel_shop-db-${BRANCH_NAME}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: bitnami/redis:7.2
    platform: linux/amd64
    ports:
        - 127.0.0.1:6379:6379
    restart: always
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL


volumes:
  storage:
  public:
  db-data:
  redis-data:
